---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy-to-cloudpanel
    image: node:20-alpine
    environment:
      DEPLOY_KEY:
        from_secret: DEPLOY_KEY
      DEPLOY_USER:
        from_secret: DEPLOY_USER
      SERVER_IP:
        from_secret: SERVER_IP
    commands:
      - npm install --global corepack@latest
      - corepack enable
      - corepack prepare pnpm@latest-10 --activate
      - pnpm config set store-dir ~/.pnpm-store
      - pnpm install --prod
      - pnpm build
      - apk add openssh git
      - mkdir -p ~/.ssh/
      - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo $DRONE_REMOTE_URL
      # - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$SERVER_IP "pwd"
      - ls -al
      - scp -r ./dist $DEPLOY_USER@$SERVER_IP:~/htdocs/blog.nipunh.com
