---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy-to-cloudpanel
    image: node:20-alpine
    commands:
      - npm install --global corepack@latest
      - corepack enable
      - corepack prepare pnpm@latest-10 --activate
      - pnpm config set store-dir ~/.pnpm-store
      - pnpm install
      - apk add openssh
      # - mkdir -p ~/.ssh/
      # - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
      # - chmod 600 ~/.ssh/id_rsa
      # - echo $DRONE_REMOTE_URL
      # - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$SERVER_IP "rm -rf /home/nipunh/tmp/portfolio && cd /home/nipunh/tmp && git clone --depth 1 $DRONE_REMOTE_URL && cd portfolio && rm -rf .* && cp -R . /home/nipunh/htdocs/nipunh.com/ && rm -rf /home/nipunh/tmp/portfolio"
